options:
  formatter: stylish
  merge-default-rules: false
files:
  include: '**/*.scss'
  # ignore: 'src/1_global-scss/vendor/**/*'
rules:
  attribute-quotes:
    - 2
    - include: true
  bem-depth:
    - 2
    - max-depth: 3
  border-zero:
    - 2
    - convention: 0
  brace-style:
    - 2
    - allow-single-line: false
  clean-import-paths:
    - 2
    - filename-extension: false
      leading-underscore: false
  declarations-before-nesting: 2
  empty-args: 2
  extends-before-declarations: 2
  extends-before-mixins: 2
  empty-line-between-blocks:
    - 2
    - include: true
      allow-single-line-rulesets: false
  final-newline: 2
  force-element-nesting: 2
  force-pseudo-nesting: 2
  function-name-format:
    - 2
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  hex-length:
    - 2
    - style: short
  hex-notation:
    - 2
    - style: lowercase
  indentation:
    - 2
    - size: 2
  leading-zero: 2
  nesting-depth:
    - 2
    - max-depth: 3
  no-css-comments: 2
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 1
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: true
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-url-domains: 0
  no-url-protocols: 0
  no-warn: 2
  one-declaration-per-line: 2
  property-sort-order: 0
  pseudo-element: 2
  quotes: 2
  shorthand-values: 2
  single-line-per-selector: 2
  space-after-bang:
    - 2
    - include: false
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon:
    - 2
    - include: false
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  zero-unit: 2
